### ISSUE TITLE
Receiving a S0C4 in BRXXTEST 2nd step: BANNER

### ISSUE THREAD

**Issue by JayMoseleyTX** [mvslovers/brexx370#77]
This is with new installation of V2R3B3. I have tried re-installing a few times with the same result. V2R2M1 has been running for a while on this system with no problem. I cannot see anything obvious. Any suggestions welcomed.

[brxxinst.pdf](https://github.com/mvslovers/brexx370/files/5592075/brxxinst.pdf)
[brxxtest.pdf](https://github.com/mvslovers/brexx370/files/5592076/brxxtest.pdf)

**Comment by mgrossmann** [comment]
Hi Jay,

glad to have you testing our brexx.
I will talk to @Peter-Jacob, tomorrow.
We have a new Beta version of V2R3 ready.
Just the packaging has to be done.

I keep you informed, here.

Mike

**Comment by Peter-Jacob** [comment]
Hello Jay,

 

Thank you for your finding. We discovered it a couple of days ago too. The problem arises because of the removal of the BREXXSTD load module from our installation process but forgot to change it in the Test JCL.   

 

The circumvention is to replace BREXXSTD by BREXX in the BREXXTEST Job. You should also remove BREXXSTD in SYS2.LINKLIB. 

 

Our apologies for the trouble!

 

The error has been corrected in the forthcoming release delivery. 

 

Regards

 

Peter 

 

Von: JayMoseleyTX <notifications@github.com> 
Gesendet: Dienstag, 24. November 2020 19:55
An: mvslovers/brexx370 <brexx370@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [mvslovers/brexx370] Receiving a S0C4 in BRXXTEST 2nd step: BANNER (#77)

 

This is with new installation of V2R3B3. I have tried re-installing a few times with the same result. V2R2M1 has been running for a while on this system with no problem. I cannot see anything obvious. Any suggestions welcomed.

brxxinst.pdf <https://github.com/mvslovers/brexx370/files/5592075/brxxinst.pdf> 
brxxtest.pdf <https://github.com/mvslovers/brexx370/files/5592076/brxxtest.pdf>

**Comment by JayMoseleyTX** [comment]
> Hi Jay,
> 
> glad to have you testing our brexx.
> I will talk to @Peter-Jacob, tomorrow.
> We have a new Beta version of V2R3 ready.
> Just the packaging has to be done.
> 
> I keep you informed, here.
> 
> Mike
> 
> P.S. Can you do a simple RX call in TSO? Is this abending, too?

Yes, if I execute a simple REXX with only a SAY in it, the script seems to execute properly, but still received the S0C4 abend.

![Screenshot_2020-11-25_07-24-03](https://user-images.githubusercontent.com/71410407/100233622-9d891400-2eef-11eb-8aeb-2da2da6df863.png)

**Comment by JayMoseleyTX** [comment]
> Hello Jay, Thank you for your finding. We discovered it a couple of days ago too. The problem arises because of the removal of the BREXXSTD load module from our installation process but forgot to change it in the Test JCL. The circumvention is to replace BREXXSTD by BREXX in the BREXXTEST Job. You should also remove BREXXSTD in SYS2.LINKLIB. Our apologies for the trouble! The error has been corrected in the forthcoming release delivery. Regards Peter

I replaced PGM=BREXXSTD with PGM=BREXX. Still receive the S0C4 abend.

**Comment by mgrossmann** [comment]
Hello, Jay,

you get the 0C4 at the end of the execution because your Hercules has not enabled the TCP/IP extension. This error has already been fixed. We have released the final version of V2R3 today. Peter is currently building the installer / archive. 
Please be patient for a moment until the new archive is available on GitHub.

Thanks for testing.

Mike

**Comment by mgrossmann** [comment]
small hint...

such simple rexx scripts can be called as:

`rx - say 'HI'`

Mike

**Comment by Peter-Jacob** [comment]
Hello Jay,

 

We have released the new BREXX/370 V2R3M0. It should resolve all problems you discovered. 

We tested explicitly the TCP cleanup problem, which arises in non-TK4 systems with deactivated TCP support.   

 

https://github.com/mvslovers/brexx370/releases/download/V2R3M0/BREXX370_V2R3M0.zip  

 

Thank you for testing!

 

Regards

 

Peter 

 

Von: JayMoseleyTX <notifications@github.com> 
Gesendet: Mittwoch, 25. November 2020 14:30
An: mvslovers/brexx370 <brexx370@noreply.github.com>
Cc: Peter-Jacob <PeterJ88@t-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [mvslovers/brexx370] Receiving a S0C4 in BRXXTEST 2nd step: BANNER (#77)

 

Hello Jay, Thank you for your finding. We discovered it a couple of days ago too. The problem arises because of the removal of the BREXXSTD load module from our installation process but forgot to change it in the Test JCL. The circumvention is to replace BREXXSTD by BREXX in the BREXXTEST Job. You should also remove BREXXSTD in SYS2.LINKLIB. Our apologies for the trouble! The error has been corrected in the forthcoming release delivery. Regards Peter

I replaced PGM=BREXXSTD with PGM=BREXX. Still receive the S0C4 abend.

**Comment by JayMoseleyTX** [comment]
Peter,

Thanks. I grabbed V2R3M0 this morning and installed it. The S0C4 abend no longer occurs.

Thanks,
Jay
